# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carla
email: celealra@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  Carla is a Management Engineering student at the University of Waterloo who is passionate about interaction design and social change. This is her portolio.
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: celealra
github_username:  jekyll

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 6
paginate_path: "blog/page:num"
